USE master
DROP DATABASE IF EXISTS MrglCRM

CREATE DATABASE MrglCRM
GO
USE MrglCRM

CREATE TABLE Users(
	[Id] INT PRIMARY KEY IDENTITY(1,1),
	[LoginName] NVARCHAR(5) NOT NULL,
	[FirstName] NVARCHAR(40) NOT NULL,
	[LastName] NVARCHAR(40) NOT NULL,
	[EMail] NVARCHAR(40) NOT NULL,
	[Hash] NVARCHAR(255) NOT NULL,
	[Role] TINYINT NOT NULL
);


CREATE TABLE Customers(
	[Id] INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(60) NOT NULL,
	[Address1] NVARCHAR(60) NOT NULL,
	[Address2] NVARCHAR(60) NOT NULL,
	[Address3] NVARCHAR(60) NOT NULL,
	[Zipcode] NVARCHAR(20) NOT NULL,
	[Country] NVARCHAR(40) NOT NULL,
	[Phone] NVARCHAR(20) NOT NULL,
	[Category] NVARCHAR(20) NOT NULL,
	[TaxNo] NVARCHAR(20) NOT NULL
);

CREATE TABLE Orders(
	[Id] INT PRIMARY KEY IDENTITY(1,1),
	[OrderDate] DATETIME NOT NULL,
	[StartDelivery] DATETIME NOT NULL,
	[EndDelivery] DATETIME NOT NULL,
	[OrderDescription] NVARCHAR(255) NOT NULL,
	[OrderRemarks] NVARCHAR(MAX) NOT NULL,
	[OrderStatus] TINYINT NOT NULL,
	[CustomerId] INT FOREIGN KEY REFERENCES Customers(Id)
);

CREATE TABLE OrderUserRel(
	[Id] INT PRIMARY KEY IDENTITY(1,1),
	[UserId] INT FOREIGN KEY REFERENCES Users(Id),
	[OrderId] INT FOREIGN KEY REFERENCES Orders(Id)
);

CREATE TABLE Attachment(
	[Id] INT PRIMARY KEY IDENTITY(1,1),
	[UserId] INT FOREIGN KEY REFERENCES Users(ID),
	[Tittle] NVARCHAR(40) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[ImageData] VARBINARY(MAX) NULL,
	[ImageType] TINYINT NOT NULL,
	[Placement] INT NOT NULL
);

CREATE TABLE AttachmentOrderRel(
	[Id] INT PRIMARY KEY IDENTITY(1,1),
	[AttachmentId] INT FOREIGN KEY REFERENCES Users(Id),
	[OrderId] INT FOREIGN KEY REFERENCES Attachment(Id)
);

CREATE TABLE Documents(
	[Id] INT PRIMARY KEY IDENTITY(1,1),
	[SketchIMG] VARBINARY(MAX) NOT NULL,
	[SketchDescription] NVARCHAR(MAX) NOT NULL,
	[ImgBefore] VARBINARY(MAX) NOT NULL,
	[DescriptionBefore] NVARCHAR(MAX) NOT NULL,
	[ImgAfter] VARBINARY(MAX) NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[UserID] INT FOREIGN KEY REFERENCES Users(Id)
);

CREATE TABLE OrderDocumentRel(
	[Id] INT PRIMARY KEY IDENTITY(1,1),
	[OrderId] INT FOREIGN KEY REFERENCES Orders(Id),
	[CustomerId] INT FOREIGN KEY REFERENCES Customers(Id)
);

CREATE TABLE Networks(
	[Id] INT PRIMARY KEY IDENTITY(1,1),
	[Network] NVARCHAR(100) NOT NULL,
	[IsIPv4] BIT NOT NULL,
	[HasPOE] BIT NOT NULL,
	[CustomerId] INT FOREIGN KEY REFERENCES Customers(Id)
);

CREATE TABLE WLAN(
	[Id] INT PRIMARY KEY IDENTITY(1,1),
	[SSID] NVARCHAR(255) NOT NULL,
	[PSK] NVARCHAR(255) NOT NULL,
	[NetworkId] INT FOREIGN KEY REFERENCES Networks(Id)
);

CREATE TABLE Devices(
	[Id] INT PRIMARY KEY IDENTITY(1,1),
	[IP] NVARCHAR(100) NOT NULL,
	[LoginUser] NVARCHAR(100),
	[LoginPass] NVARCHAR(100),
	[IsPOE] BIT NOT NULL,
	[NetworkId] INT FOREIGN KEY REFERENCES Networks(Id)
);
